### ISSUE TITLE
Extension throws error after some time

### ISSUE THREAD

**Issue by domsle** [zagortenay333/cronomix#16] opened 2017-08-13 07:18 UTC
Hello,
I am completely hopeless here.
My problem is, that after some time of using my pc time++ just stops working, and there is an error icon next to enable toggle in gnome tweaks.
After I reboot my PC, or manually delete extension and add it again, it works again.

Could you help?

**Comment by zagortenay333** [comment] 2017-08-13 08:06
There's no way I can help you with that report; I need more information.

When it crashes, open a terminal and check the output of:
```
journalctl /usr/bin/gnome-shell -r | less
```
_If you use the gnome-terminal, select everything and `ctrl-shift-c` to copy it and then use a website like pastebin to show me the logs.
Or you can search the prog yourself; use `/` to search for `timepp` or `time`, and see if there are any bugs. Hit `q` to quit._

Are you using the latest version from master?
When/how does it crash? Do you just log into your pc one day, and the extension is not loaded, or does it happen after you unlock the screen (check this issue: #9.)
How many times did it happen so far? After how much time do you have to delete it?

**Comment by domsle** [comment] 2017-08-14 07:14
[Here](https://pastebin.com/S6xwuWpL) is output of:
`journalctl /usr/bin/gnome-shell -r | grep timepp`
Is this helpful?
I use version cloned 2 weeks ago. I updated it right now, because maybe you fixed it already?

I think it happens after some time of using Gnome. After a reboot it works again. Locking screen, or putting pc to sleep does not cause this to happen.
It is hard to tell how long it takes for it to crash.

**Comment by zagortenay333** [comment] 2017-08-14 08:04
Tell me if you have the same problem with the updated version.

This actually does look similar to that issue I linked above, and I have no clue what causes it. As you can see in that issue, it just went away after a while..

When does it happen though? Does the extension just crash suddenly, or do you do something to trigger it like locking the screen?

**Comment by domsle** [comment] 2017-08-15 15:08
I updated it, and now it still happens. Maybe it happens a bit less often.
I have seriously no idea when this happens. For me it just stops working after some undefined period of time. I use your extension mostly to store my tasks, and sometimes use Pomodoro - it is most time just in idle. So it crashes suddenly, out of nothing.
For past few days I am having some problem with Wayland, and after it crashed extension works again just fine, just as if I rebooted.

**Comment by zagortenay333** [comment] 2017-08-15 20:11
The other person also uses Wayland.; I don't. Maybe that's the issue. Based on your journal entry, it's not a bug that is in the scope of this extension. :/

**Comment by zagortenay333** [comment] 2017-08-15 20:12
Don't know what to say.

**Comment by zagortenay333** [comment] 2017-08-15 20:17
Btw, are you changing your gnome-shell themes often?

**Comment by zagortenay333** [comment] 2017-08-15 20:19
Is the language on your comp English?

**Comment by domsle** [comment] 2017-08-15 20:19
No i don't. I changed it like a week ago. Why do you ask? 
So you do not have any idea of what could be causing this issue?

**Comment by domsle** [comment] 2017-08-15 20:19
It is Polish.

**Comment by zagortenay333** [comment] 2017-08-15 20:21
I have exactly 0 clue as to what's going on.

**Comment by zagortenay333** [comment] 2017-08-15 20:22
Have you disabled certain section (timer, alarms...)?

**Comment by domsle** [comment] 2017-08-15 20:25
Exactly these two are disabled. I use only Pomo and Tasks.

**Comment by zagortenay333** [comment] 2017-09-01 13:14
Are you still using the extension? Have you encountered the same problem?

**Comment by domsle** [comment] 2017-09-01 18:33
Yes I do. So far after updating to latest version I think it works fine.

**Comment by zagortenay333** [comment] 2017-09-01 18:35
Are you using the version with the new stats view? Fingers crossed it doesn't crash again. :crossed_fingers:

**Comment by zagortenay333** [comment] 2017-09-04 08:03
I'm closing this for now. If you experience the bug again, feel free to reopen this issue.

**Closed as completed by zagortenay333** 2017-09-04 08:03 UTC
